siglas = {
          #serie a
          'ATH': ('Athletico Paranaense - PR','a'),
          'AME': ('America Fc S.a.f. - MG','a'),
          'BAH': ('Bahia - BA','a'), 
          'BOT': ('Botafogo - RJ','a'),
          'CAM': ('Atlético Mineiro - MG','a'),
          'CEC': ('Cruzeiro Saf - MG','a'),
          'CFC': ('Coritiba S.a.f. - PR','a'),
          'COR': ('Corinthians - SP','a'),
          'CUI': ('Cuiabá Saf - MT','a'),
          'FLA': ('Flamengo - RJ','a'),
          'FLU': ('Fluminense - RJ','a'),
          'INT': ('Internacional - RS','a'),
          'GOI': ('Goiás - GO','a'),
          'GRE': ('Grêmio - RS','a'),
          'PAL': ('Palmeiras - SP','a'),
          'RDB': ('Red Bull Bragantino - SP','a'),
          'SAN': ('Santos - SP','a'),
          'SAO': ('São Paulo - SP','a'),
          'FOR': ('Fortaleza - CE','a'),
          'VAS': ('Vasco da Gama S.a.f. - RJ','a'),

          #serie b
          'ABC': ('Abc - RN','b'),
          'AGO': ('Atlético - GO','b'), 
          'AVA': ('Avaí - SC','b'),
          'BFC':('Botafogo - SP','b'),
          'CEA': ('Ceará - CE','b'),
          'CHA': ('Chapecoense - SC','b'),
          'CRB': ('Crb - AL','b'),
          'CRI': ('Criciúma - SC','b'),
          'GUA': ('Guarani - SP','b'), 
          'ITU': ('Ituano - SP','b'),
          'JUV': ('Juventude - RS','b'), 
          'SPO': ('Sport - PE','b'),
          'VIL': ('Vila Nova - GO','b'),
          'VIT': ('Vitória - BA','b'),
          'SAM': ('Sampaio Corrêa - MA','b'),
          'TOM': ('Tombense - MG','b'),
          'LON': ('Londrina - PR','b'),
          'PON': ('Ponte Preta - SP','b'),
          'MIR':('Mirassol - SP','b'),
          'NOV': ('Novorizontino - SP','b'),
         
    }
