siglas = {'FOR': ('Fortaleza - CE','a'), 
          'ATH': ('Athletico Paranaense - PR','a'), 
          'AGO': ('Atlético - GO','a'),
          'BRA': ('Red Bull Bragantino - SP','a'),
          'BAH': ('Bahia - BA','a'),
          'FLU': ('Fluminense - RJ','a'),
          'PAL': ('Palmeiras - SP','a'),
          'FLA': ('Flamengo - RJ','a'),
          'CAM': ('Atlético Mineiro - MG','a'),
          'COR': ('Corinthians - SP','a'),
          'CEA': ('Ceará - CE','a'),
          'SAN': ('Santos - SP','a'),
          'CUI': ('Cuiabá - MT','a'),
          'SPO': ('Sport - PE','a'),
          'SAO': ('São Paulo - SP','a'),
          'JUV': ('Juventude - RS','a'),
          'INT': ('Internacional - RS','a'),
          'GRE': ('Grêmio - RS','a'),
          'AME': ('America - MG','a'),
          'CHA': ('Chapecoense - SC','a'),
          'CEC': ('Cruzeiro - MG','b'),
          'BRU': ('Brusque - SC','b'),
          'NAU': ('Náutico - PE','b'),
          'GUA': ('Guarani - SP','b'),  
          'BOT': ('Botafogo - RJ','b'),
          'GOI': ('Goiás - GO','b'),
          'CRB': ('Crb - AL','b'),
          'REM': ('Remo - PA','b'),
          'CON': ('Confiança - SE','b'),
          'CFC': ('Coritiba - PR','b'),
          'OPE': ('Operário - PR','b'),
          'VIL': ('Vila Nova - GO','b'),
          'SAM': ('Sampaio Corrêa - MA','b'),
          'POM': ('Ponte Preta - SP','b'),
          'VIT': ('Vitória - BA','b'),
          'GEB': ('Brasil - RS','b'),
          'CSA': ('Csa - AL','b'),
          'LON': ('Londrina - PR','b'),
          'VAS': ('Vasco da Gama - RJ','b'),
          'AVA': ('Avaí - SC','b')
                        }
