siglas = {'FOR': 'Fortaleza - CE', 
          'ATH': 'Athletico Paranaense - PR', 
          'AGO': 'Atlético - GO',
          'BRA': 'Red Bull Bragantino - SP',
          'BAH': 'Bahia - BA',
          'FLU': 'Fluminense - RJ',
          'PAL': 'Palmeiras - SP',
          'FLA': 'Flamengo - RJ',
          'CAM': 'Atlético Mineiro - MG',
          'COR': 'Corinthians - SP',
          'CEA': 'Ceará - CE',
          'SAN': 'Santos - SP',
          'CUI': 'Cuiabá - MT',
          'SPO': 'Sport - PE',
          'SAO': 'São Paulo - SP',
          'JUV': 'Juventude - RS',
          'INT': 'Internacional - RS',
          'GRE': 'Grêmio - RS',
          'AME': 'America - MG',
          'CHA': 'Chapecoense - SC',
          'CEC': 'Cruzeiro - MG',
          'BRU': 'Brusque - SC',
          'NAU': 'Náutico - PE',
          'GUA': 'Guarani - SP',   
          'BOT': 'Botafogo - RJ',
          'GOI': 'Goiás - GO',
          'CRB': 'Crb - AL',
          'REM': 'Remo - PA',
          'CON': 'Confiança - SE',
          'CFC': 'Coritiba - PR',
          'OPE': 'Operário - PR',
          'VIL': 'Vila Nova - GO',
          'SAM': 'Sampaio Corrêa - MA',
          'POM': 'Ponte Preta - SP',
          'VIT': 'Vitória - BA',
          'GEB': 'Brasil - RS',
          'CSA': 'Csa - AL',
          'LON': 'Londrina - PR',
          'VAS': 'Vasco da Gama - RJ',
          'AVA': 'Avaí - SC'
                        }
